# Generated by Django 5.2.8 on 2025-11-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneixuserdata',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
